# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d206674165b4f364bbafa9af3e2ed89afd5371e1da11557bae032b2f7fdd978d588d23b8a7005be78cd46ea99e3ba91bc8f94615de39a7b6d674b1e8e49380e

test:
  secret_key_base: 5aa940efd8d4767783d05b2979476d0d34a04a243732f969c6cb39d59456c8bd60dde9c2d87b66fb00007c7f7d11a243a9519f5439e7092659176292c74e489e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
